export const SCHEMA = {
  1:{type:'string',max:31,label:'Device name',desc:'Name shown in HID descriptor. Shows up in device list. Keep under 31 chars.'},
  2:{type:'string',max:31,label:'Manufacturer',desc:'Manufacturer string for USB descriptor. Cosmetic only.'},
  3:{type:'string',max:15,label:'Serial number',desc:'Serial string, max 15 chars. Helps tell two mice apart.'},
  4:{type:'string',max:15,readonly:true,label:'Firmware version',desc:'Current firmware version burned into flash. Read only.'},
  16:{type:'bool',label:'Sensor module',desc:'Enable or disable the PMW3360 sensor stack. If off, mouse stops tracking.'},
  17:{type:'bool',label:'Buttons module',desc:'Enable the main click handling. Turn off if you are debugging USB only.'},
  18:{type:'bool',label:'Scroll module',desc:'Enable scroll wheel decoding. Disable if wheel is not fitted.'},
  19:{type:'bool',label:'HyprX module',desc:'Enable HyprX engine that turns scroll into rapid clicks when side macro is held.'},
  20:{type:'bool',label:'LEDs module',desc:'Enable the 2 LEDs driver. Saves power when off.'},
  21:{type:'bool',label:'SOF sync module',desc:'Throttle polling to USB SOF. When on, 1kHz polling is synced to USB frames for lower jitter.'},
  32:{type:'u16',min:100,max:32000,label:'DPI',desc:'Sensor sensitivity. 100 to 32000. Higher is faster cursor. Typical 400-1600 for games.'},
  33:{type:'enum',values:[125,250,500,1000,2000,4000,8000],label:'Polling rate',desc:'How often mouse reports to PC. 1000 Hz is 1ms. Higher uses more CPU.'},
  34:{type:'u8',min:1,max:3,label:'Lift-off distance',desc:'How high you can lift before sensor stops. 1mm low, 3mm high. Lower is better for most.'},
  35:{type:'u8',min:10,max:200,label:'Surface tuning SQUAL',desc:'Minimum SQUAL to keep tracking. Higher = more strict, prevents tracking on bad surfaces.'},
  36:{type:'bool',label:'Angle snapping',desc:'Straightens near-horizontal and vertical lines. Usually off for gaming.'},
  37:{type:'u8',min:0,max:100,label:'Angle snap strength',desc:'How strong the angle correction is when snapping is on. 0 to 100.'},
  38:{type:'enum',values:[0,1,2,3],label:'Surface preset',desc:'Preset for surface type: 0 default, 1 cloth, 2 hard pad, 3 custom.'},
  48:{type:'u8',min:0,max:20,label:'Left click debounce',desc:'Debounce for PB3 left click. Milliseconds. Higher stops double clicks but adds lag. 4 is good.'},
  49:{type:'u8',min:0,max:20,label:'Right click debounce',desc:'Debounce for PB4 right click. Same as left.'},
  50:{type:'u8',min:0,max:20,label:'Middle click debounce',desc:'Debounce for PB5 scroll click.'},
  51:{type:'u8',min:0,max:20,label:'Side button debounce',desc:'Debounce for PB6 side button.'},
  52:{type:'u8',min:0,max:20,label:'PIO button debounce',desc:'Debounce for PB7 programmable button. Usually a bit higher, 8ms.'},
  53:{type:'enum',values:[0,1,2],label:'Click mode',desc:'0 normal, 1 rapid fire, 2 custom timing. Changes how clicks are sent.'},
  64:{type:'u8',min:1,max:8,label:'Scroll divisor',desc:'Divide scroll steps. 1 is 1:1, 2 needs two detents for one scroll tick.'},
  65:{type:'bool',label:'Scroll direction',desc:'Normal or inverted scroll. Flip if wheel feels backwards.'},
  66:{type:'bool',label:'Scroll smoothing',desc:'Smooth out noisy encoder. Turn on if scroll jitters.'},
  80:{type:'bool',label:'HyprX enable',desc:'Master switch for HyprX. When off, side button does not trigger HyprX.'},
  81:{type:'bool',label:'HyprX uses macro LED',desc:'If on, LED changes to macro colour when HyprX is active. Easy visual feedback.'},
  82:{type:'enum',values:[0,1],label:'HyprX target button',desc:'Which button HyprX spams: left or right click.'},
  83:{type:'u8',min:1,max:24,label:'Steps to trigger click',desc:'How many scroll detents before one click fires in HyprX. Lower is faster.'},
  84:{type:'u8',min:1,max:4,label:'HyprX divisor',desc:'Extra divisor for HyprX speed. 1 is fastest.'},
  85:{type:'u16',min:0,max:500,label:'HyprX hold time',desc:'How long HyprX holds the click in ms. 40ms feels natural.'},
  96:{type:'rgb',label:'LED default colour',desc:'Normal LED colour. Hex #rrggbb.'},
  97:{type:'rgb',label:'LED macro colour',desc:'LED colour when macro or HyprX is active.'},
  98:{type:'u8',min:0,max:255,label:'LED brightness',desc:'0 off, 255 max. 128 is balanced.'},
  99:{type:'enum',values:[0,1,2,3,4],label:'LED effect',desc:'0 static, 1 breathing, 2 pulse, 3 static alt, 4 off.'},
  100:{type:'u8',min:0,max:255,label:'LED speed',desc:'Speed for breathing and pulse effects. Higher is faster.'},
  112:{type:'enum',values:[0,1,2,3,4],label:'Side button action',desc:'What PB7 does: 0 types Program Me, 1 mouse button, 2 keyboard key, 3 key combo up to 8 keys, 4 media key.'},
  113:{type:'enum',values:[0,1,2,3],label:'Side button AT legacy',desc:'Legacy field kept for compat. Usually 0.'},
  114:{type:'enum',values:[0,1,2,3,4,5,6,7],label:'Mouse button',desc:'Which mouse button PB7 acts as when mode is mouse.'},
  115:{type:'u8',min:0,max:255,label:'Keyboard key',desc:'HID key code for PB7 when mode is key. 65 is A.'},
  116:{type:'combo',label:'Key combo',desc:'Up to 8 HID codes comma separated, e.g. 224, 4 is Ctrl+A.'},
  117:{type:'enum',values:[0,1,2,3,4,5,6,7,8,9,10,11,12],label:'Media key',desc:'Media control when mode is media: 0-12 for play, volume etc.'},
};

export const TABS = {
  profiles:[], // virtual
  device:[1,2,3,4,16,17,18,19,20,21],
  sensor:[32,33,34,35,36,37,38],
  buttons:[48,49,50,51,52,53],
  scroll:[64,65,66],
  lights:[96,97,98,99,100],
  hyprx:[80,81,82,83,84,85],
  pio:[112,113,114,115,116,117],
};
