#pragma once
#define BUILD_FLAG_NO_SENSOR 1
#define BUILD_FLAG_HAS_TACTILE 1
#define BUILD_FLAG_HAS_LIGHTS 1
#define BUILD_FLAG_HAS_HYPRX 1
#define BUILD_FLAG_HAS_USB 1
#define BUILD_FLAG_HAS_CONFIG 1
#define BUILD_FLAG_MCU_SPEED_OPT 1
#define BUILD_FLAG_LTO 1
